# 이름: 정다솔
# 학번: 2017310367
# 학과: 문헌정보학과

##### presidents DataFrame

In [2]:
import pandas as pd
import numpy as np
president_data  = {'name': ['이승만', '윤보선', '박정희', '최규하', '전두환', '노태우',
                       '김영삼', '김대중', '노무현', '이명박', '박근혜', '문재인'],
        'turnout': [91.8, 79.1, 46.6, 96.3, 99.4, 36.6,
                    42, 40.3, 48.9, 48.7, 51.6,41.1],
        'jail': ['no', 'no', 'no', 'no', 'yes', 'yes',
                'no', 'no', 'no','yes','yes',np.nan],
        'period':[4273, 588, 5793, 255, 2733, 1827, 1826, 1825, 1826, 1827, 1474, 1780]}
labels = ['가', '나', '다', '라', '마', '바', '사', '아', '자', '차','카','타']
presidents = pd.DataFrame(president_data, index=labels )

### Q1. 위 presidents DataFrame에서 대통령을 period(재임기간) 5년 미만, 5년 이상 ~ 10년 미만, 10년 이상을 기준으로 Grouping 하고 그룹별로 turnout(득표율)의 평균을 Series로 보여주는 코드를 작성하세요.

In [7]:
presidents.head(20)

  name  turnout jail  period
가  이승만     91.8   no    4273
나  윤보선     79.1   no     588
다  박정희     46.6   no    5793
라  최규하     96.3   no     255
마  전두환     99.4  yes    2733
바  노태우     36.6  yes    1827
사  김영삼     42.0   no    1826
아  김대중     40.3   no    1825
자  노무현     48.9   no    1826
차  이명박     48.7  yes    1827
카  박근혜     51.6  yes    1474
타  문재인     41.1  NaN    1780

In [10]:
presidents.groupby(
    pd.cut(presidents['period'],[0, 1825, 3650, presidents['period'].max()+1], labels=['5년 미만', '5년 이상 ~ 10년 미만', '10년 이상']) #(0~1825]는 5년 미만, (1825~3650]은 5년 이상 ~ 10년 미만, (3650, ~]은 10년 이상
)['turnout'].mean()

period
5년 미만             61.68
5년 이상 ~ 10년 미만    55.12
10년 이상            69.20
Name: turnout, dtype: float64

### Q2. 위 presidents DataFrame에서 1. turnout(득표율) 50% 미만/이상, 2. jail(대통령 역임 후 수감) 여부   2가지로 Grouping하고 그룹별로 period(재임기간)의 평균을 Series로 보여주는 코드를 작성하세요.

In [12]:
presidents.groupby(
   [pd.cut(presidents['turnout'],[0, 50, 100], labels=['50% 미만', '50% 이상']), 'jail']
)['period'].mean()

turnout  jail
50% 미만   no      2817.500000
         yes     1827.000000
50% 이상   no      1705.333333
         yes     2103.500000
Name: period, dtype: float64

### Q3. 다음 인종실록 데이터에서 category(기사주제)의 숫자를 기준으로 Grouping하고, 그룹별로 content_length(기사 길이)의 평균을 Series로 보여주는 코드를 작성하세요.

In [25]:
injong_sillok = pd.read_csv('injong_sillok.csv')
# your code here

injong_sillok.head(20)

,url,title,content,category
0,http://sillok.history.go.kr/id/kla_10101001_001,삭전을 지내고 상식을 올리다,상이 삭전 을 지내고 상식 을 올렸다.이에 앞서는 삭망전과 별제 를 대군 ...,['왕실(王室)']
1,http://sillok.history.go.kr/id/kla_10101001_002,햇무리가 지다,햇무리가 졌다.,['과학-천기(天氣)']
2,http://sillok.history.go.kr/id/kla_10101002_001,조석전을 지내고 상식을 올리다,상이 조석전을 지내고 상식을 올렸다.,['왕실(王室)']
3,http://sillok.history.go.kr/id/kla_10101002_002,좌의정 홍언필이 사직을 청하다,"좌의정 홍언필이 아뢰기를,""신은 장구나 따지는 하찮은 선비로서 어쩌다가 과제에 들...","['왕실(王室)', '정론(政論)', '인사(人事)', '역사-사학(史學)']"
4,http://sillok.history.go.kr/id/kla_10101002_003,헌부가 중종의 시호를 빨리 정할 것과 이인현·정웅의 체직을 청하다,"헌부가 아뢰기를,""의시 는, 조종 때에는 하루에 다 의논하여 정하였는데 이번 대행...","['왕실(王室)', '정론(政論)', '인사(人事)', '사법(司法)']"
5,http://sillok.history.go.kr/id/kla_10101002_004,이조 정랑 윤희성의 졸기,"정원이 아뢰기를,""이조 정랑 윤희성이 지난달 그믐날에 죽었습니다. 대행 대왕 때에는...","['왕실-사급(賜給)', '인물(人物)']"
6,http://sillok.history.go.kr/id/kla_10101003_001,조석전을 지내고 상식을 올리다,상이 조석전을 지내고 상식을 올렸다.,['왕실(王室)']
7,http://sillok.history.go.kr/id/kla_10101003_002,홍언필이 다시 사직을 청하다,"좌의정 홍언필이 아뢰기를,""신의 마음을 죄다 아뢰었으므로 다시 말할 것이 없습니다...","['왕실(王室)', '정론(政論)', '인사(人事)']"
8,http://sillok.history.go.kr/id/kla_10101003_003,헌부가 송겸·임세무의 추고를 청하다,"헌부가 아뢰기를,""모든 공사 의 출입은 반드시 정원을 거치게 해야만이 정령을 내고...","['왕실(王室)', '정론(政論)', '인사(人事)', '사법-탄핵(彈劾)']"
9,http://sillok.history.go.kr/id/kla_10101004_001,조석전을 지내고 상식을 올리다,상이 조석전을 지내고 상식을 올렸다.,['왕실(王室)']
10,http://sillok.history.go.kr/id/kla_10101004_002,우의정 윤인경에게 시호를 빨리 정할 것을 전교하다,"우의정 윤인경에게 전교하기를,""의시에 대한 일은 오래도록 거행하지 못하였으므로 내...","['왕실(王室)', '정론-정론(政論)']"
11,http://sillok.history.go.kr/id/kla_10101004_003,"간원이 승지의 체직을, 헌부가 혼전을 정할 것을 청하다","간원이 아뢰기를,""수릉관과 시릉관 등은 망극한 일을 당한 처음에 사사로운 부탁을 받...","['왕실(王室)', '정론-간쟁(諫諍)', '인사(人事)', '사법-탄핵(彈劾)']"
12,http://sillok.history.go.kr/id/kla_10101004_004,헌부에서 창덕궁으로 옮길 것을 청하다,"헌부가 또 아뢰기를,""이제 자전께서 그대로 창경궁에 계시므로 전하께서도 거기에서 가...","['왕실(王室)', '정론-간쟁(諫諍)', '인사(人事)', '사법(司法)']"
13,http://sillok.history.go.kr/id/kla_10101005_001,조석전을 지내고 상식을 올리다,상이 조석전을 지내고 상식을 올렸다.,['왕실(王室)']
14,http://sillok.history.go.kr/id/kla_10101005_002,우의정 윤인경 등이 의논하여 시호를 정하다,"우의정 윤인경, 좌찬성 이기, 우찬성 성세창, 이조 판서 신광한, 호조 판서 임백...","['왕실(王室)', '정론-정론(政論)', '역사-사학(史學)', '역사-고사(故事)']"
15,http://sillok.history.go.kr/id/kla_10101005_003,대간과 헌부가 송겸·임세무·승지 등과 남효의의 일을 아뢰다,"대간이 송겸·임세무·승지 등의 일을 아뢰고, 헌부가 남효의의 일을 아뢰니, 답하였다...","['왕실(王室)', '정론-간쟁(諫諍)', '사법-탄핵(彈劾)']"
16,http://sillok.history.go.kr/id/kla_10101005_004,부제학 송세형 등이 올린 간관의 역할 등에 관한 차자,"부제학 송세형 등이 차자를 올리기를,""지극히 광대한 일과 지극히 중요한 기틀에 대...","['왕실(王室)', '정론-간쟁(諫諍)', '인사(人事)', '사법(司法)']"
17,http://sillok.history.go.kr/id/kla_10101006_001,조석전을 지내고 상식을 올리다,상이 조석전을 지내고 상식을 올렸다.,['왕실(王室)']
18,http://sillok.history.go.kr/id/kla_10101006_002,시호를 중조로 고치는 것에 관해 전교하다,"우의정 윤인경, 좌찬성 이기, 우찬성 성세창, 좌참찬 권벌, 병조 판서 정옥형, ...","['왕실(王室)', '정론-정론(政論)', '의생활(衣生活)', '역사-고사(故事)']"
19,http://sillok.history.go.kr/id/kla_10101006_003,윤인경이 중국 사신의 원접사 문제를 아뢰다,"윤인경이 아뢰기를,""중국 사신을 지대하는 일은, 원접사와 관반을 차출한 뒤에야 모...","['인사(人事)', '외교-명(明)']"

In [26]:
injong_sillok['category'] = injong_sillok['category'].apply(eval)
injong_sillok['category'] = injong_sillok['category'].str.len()
injong_sillok['content_length'] = injong_sillok['content'].apply(len)

injong_sillok.head(10)

,url,title,content,category,content_length
0,http://sillok.history.go.kr/id/kla_10101001_001,삭전을 지내고 상식을 올리다,상이 삭전 을 지내고 상식 을 올렸다.이에 앞서는 삭망전과 별제 를 대군 ...,1,81
1,http://sillok.history.go.kr/id/kla_10101001_002,햇무리가 지다,햇무리가 졌다.,1,8
2,http://sillok.history.go.kr/id/kla_10101002_001,조석전을 지내고 상식을 올리다,상이 조석전을 지내고 상식을 올렸다.,1,20
3,http://sillok.history.go.kr/id/kla_10101002_002,좌의정 홍언필이 사직을 청하다,"좌의정 홍언필이 아뢰기를,""신은 장구나 따지는 하찮은 선비로서 어쩌다가 과제에 들...",4,1642
4,http://sillok.history.go.kr/id/kla_10101002_003,헌부가 중종의 시호를 빨리 정할 것과 이인현·정웅의 체직을 청하다,"헌부가 아뢰기를,""의시 는, 조종 때에는 하루에 다 의논하여 정하였는데 이번 대행...",4,451
5,http://sillok.history.go.kr/id/kla_10101002_004,이조 정랑 윤희성의 졸기,"정원이 아뢰기를,""이조 정랑 윤희성이 지난달 그믐날에 죽었습니다. 대행 대왕 때에는...",2,740
6,http://sillok.history.go.kr/id/kla_10101003_001,조석전을 지내고 상식을 올리다,상이 조석전을 지내고 상식을 올렸다.,1,20
7,http://sillok.history.go.kr/id/kla_10101003_002,홍언필이 다시 사직을 청하다,"좌의정 홍언필이 아뢰기를,""신의 마음을 죄다 아뢰었으므로 다시 말할 것이 없습니다...",3,880
8,http://sillok.history.go.kr/id/kla_10101003_003,헌부가 송겸·임세무의 추고를 청하다,"헌부가 아뢰기를,""모든 공사 의 출입은 반드시 정원을 거치게 해야만이 정령을 내고...",4,1066
9,http://sillok.history.go.kr/id/kla_10101004_001,조석전을 지내고 상식을 올리다,상이 조석전을 지내고 상식을 올렸다.,1,20

In [27]:
injong_sillok.groupby('category')['content_length'].mean()

category
1     129.885827
2     526.405556
3     492.888889
4     742.000000
5    1260.607143
6    1572.666667
7    2747.000000
8    5764.400000
Name: content_length, dtype: float64